# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Main Branch Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Instalando a JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compilar Main com o Java
      run: javac -cp src ./src/Main.java
      
    - name: Compilar Teste com o Java
      run: javac -cp src ./src/Teste.java
      
    - name: Executando o Teste
      run: |
        cd src
        java Teste

    - name: Retrieve metadata
      id: metadata
      uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        images: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
          type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
          type=semver,pattern={{major}},value=${{ env.TAG }}

      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
          image: oinerte/evento_jbs_image
          tags: ${{ steps.docker_meta.outputs.tags }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USUARIO_SECRETO }}
          password: ${{ secrets.DOCKER_SENHA_SECRETA }}
